# Konfiguracja Dependabot dla projektu SAKS
version: 2
updates:
  - package-ecosystem: "pip" # System pakietów dla Pythona
    directory: "/saks_beta"  # Ścieżka do SAKS
    schedule:
      interval: "weekly"     # Sprawdzaj aktualizacje raz w tygodniu
      day: "monday"
    open-pull-requests-limit: 10
    target-branch: "main"
