# Konfiguracja Dependabot dla projektu SAKS
version: 2
updates:
  - package-ecosystem: "pip" # System pakietów dla Pythona
    directory: "/saks_beta"  # Ścieżka do SAKS
    schedule:
      interval: "weekly"     # Sprawdzaj aktualizacje raz w tygodniu
    open-pull-requests-limit: 5 # Nie otwieraj więcej niż 5 zgłoszeń naraz
